requirements.txt
sockpuppet/channel.py
sockpuppet/consumer.py
sockpuppet/utils.py

We were missing to add `last` when broadcasting to cable ready, an attribute that is needed later in javascript. It also didn't transform the keys entirely correctly to `camelCase`. 
Using the inflector library it'll convert `data-controller` to `dataController` something that we are not interested in. So we roll our own. 
We also make a recursive call so that an entire list or object gets all their keys transformed correctly.

Fix that javascript not triggering correctly after reflex

---

README.md

I poked at various urls on the docs website to find this, but no luck.

:pencil: Adds local quickstart reference

---

sockpuppet/consumer.py

When making a partial dom update it's more important that it's using innerhtml. As per this answer using `decode_contents` is the correct approach for beautifulsoup.

Html should take the innerhtml to be correct

---

README.md
cypress/integration/websocket_spec.js
javascript/stimulus-websocket/index.js
package-lock.json
package.json
sockpuppet/channel.py
sockpuppet/consumer.py
sockpuppet/reflex.py
tasks.py
tests/example/javascript/example.js
tests/example/reflexes/example_reflex.py
tests/example/templates/example.html
tests/example/views/example.py
tests/settings.py
tests/test_javascript.py
webpack.config.js

The following PR adds a number of features and improvements. 
- You can subscribe and unsubscribe from other channels. The default is still that you'll be subscribed to a channel that is the user session. 
- By overriding the method `get_channel_id` in the reflex you can decide to what channel you want to broadcast to. 
- We now also use the same handlers that stimulus-reflex uses. Ie we use received and connected. 
Closes #28 Closes #6

Get django-sockpuppet up to par with SR 3.3.0

---

docs/quickstart-django.md

There was some leftover ruby from when I copied the docs. So now that's been removed.

Remove some stray ruby in the docs

---

cypress/integration/websocket_spec.js
package-lock.json
sockpuppet/consumer.py

The javascript for stimulus-reflex changed the parameter `permanent_attribute_name` to permanentAttributeName`. So this PR aims to fix this incompatibility.

Introduce compatibility with stimulus-reflex 3.4

---

tox.ini

We want to always install the latest javascript for stimulus-reflex so that we can catch any regressions and take these into account at a later stage.

Always install the latest stimulus-reflex in CI

---

sockpuppet/channel.py
sockpuppet/consumer.py
sockpuppet/reflex.py

Bugfix
The issue being that frontend identifies a json structure for the
identifier, and when stringifying a json there is no space.
In python when dumping a json there is a space. So there is a
mismatch when comparing the identifiers and so no subscription
is found.

When using the channel separately to broadcast frontend should listen

---

sockpuppet/management/commands/initial_sockpuppet.py

package.json is not currently being generated as part of `python manage.py initial_sockpuppet`.
add npm init -y to the initialize script in order to generate package.json.
if package.json is not present at the moment that python manage.py initial_sockpuppet runs, it will generate the package-lock.json and webpack.conf.json but not the package.json for maintaining dependencies

generate package.json as part of inital_sockpuppet command

---

requirements_dev.txt
sockpuppet/consumer.py

1. Update requirements_dev.txt to include base requirements, as
these are necessary for starting the server and performing any tests.
2. Use Reflex.__subclasses__() rather than name checking for reflex
subclass detection, which will be more consistent and allow users
to name their reflexes whatever they want.
3. Clear falsey values from the filepaths detected in the
load_reflexes_from_config function, which is a tenuous solution to
not including vim-generated dotfiles in the module loading process.
Bugfix and enhancement

Fixes to SocketpuppetConsumer for handling dotfiles

---

README.md
docs/setup-django.md
setup.py
sockpuppet/consumer.py
sockpuppet/utils.py

If you install sockpuppet with
```
pip install django-sockpuppet[lxml]
```
It will install everything that is required for django-sockpuppet to use the lxml parser when parsing all html fragments. This typically saves between 30-90ms depending on the complexity of the html we are parsing. 
Needs some more testing with sockpuppet expo so that we actually have the same behaviour. Saw that there was some issues with the calendar view. 
Fixes #46 
If you want a faster experience you can get one, if you're not able to install lxml (for whatever reason) you'll still be able to use beautiful soup.

If lxml and cssselect is installed we use them for better perf.

---

sockpuppet/templates/sockpuppet/scaffolds/template.html

#Fix
after running generate reflex.
This error shows up in the reflex code
Please include a summary of the change and which issue is fixed.
based on [this answer](https://stackoverflow.com/questions/42237388/syntaxerror-import-declarations-may-only-appear-at-top-level-of-a-module). I added the type="module" to the template.
Fixes # (issue)
Explain value.

fix template syntax error

---

sockpuppet/consumer.py

If `reflex_message()` fails to find a Reflex for whatever reason, it throws an exception. The code handling the exception expects the `reflex` variable to have been set, but in this method that variable only gets set inside the `try` block, so by definition it doesn't exist if the exception needs to be handled. `self.broadcast_error()` mandates the Reflex as a positional argument, but has conditional logic inside it that handles a case where the variable is falsey, so passing `None` in that spot solves the problem. I also added a little more detail to the text of the error message.
Fixes #52

Bug fix: Better recovery when a Reflex isn't found.

---

package-lock.json
package.json
sockpuppet/consumer.py
tests/example/javascript/example.js
tests/example/management/commands/progressbar.py
tests/example/templates/progressbar.html
tests/example/urls.py
tests/example/views/example.py
tests/settings.py

enhancement
This adds an out of band example of how to use django-sockpuppet. It's worth noting that the redis channel layer is a requirement for this to work (besides, redis should always be used in a production environment). 
To test this out
- Fork the library
- Install all requirements_dev.txt
- run `python manage.py runserver`
- run `npm run build:watch`
- go to http://localhost:8000/progress
- run `python manage.py progressbar`
- behold the progressbar being filled each second. 
Related to #77 
I was asked for an example :)

Out of band example

---

cypress/integration/websocket_spec.js
cypress/support/index.js
sockpuppet/channel.py
sockpuppet/consumer.py
sockpuppet/templates/sockpuppet/scaffolds/template.html
tests/example/javascript/example.js
tests/example/reflexes/example_reflex.py
tests/example/templates/error.html
tests/example/templates/param.html
tests/example/urls.py
tests/example/views/example.py

Bugfix
This amends the error logging on both frontend end backend. Frontend needed a slightly different structure for the error logging to work. 
For backend we don't raise an error, because when we do it disconnects the server, so it's better to catch the error and log it as an exception. That way we don't have any issues of sending the error message to frontend which we had prior to this. 
Semi-related to #3 
Gives clearer error messaging for both frontend and backend.

Proper error logging for frontend and backend

---

cypress/integration/websocket_spec.js
sockpuppet/reflex.py
tests/example/reflexes/example_reflex.py
tests/example/templates/param.html
tests/example/urls.py
tests/example/views/example.py

Some views may have a 'setup' in the get part of
the view. For instance ListView expects that object_list
is added to self during the get request.
So if we get an AttributeError during the reflex we
execute the actual get request there, and then go on
to generate the context view.
It's a bug.

object_list now works for ListView and similar views

---

sockpuppet/management/commands/initial_sockpuppet.py

bug fix
overwrite existing files/links when re-installing an existing add-project-script library globally
Fixes #80 
the management command `initial_sockpuppet` fails when add-project-script is already installed.

force npm install add-project-script

---

docs/persistence.md
sockpuppet/reflex.py

When adding `get_context_data` to the reflex class I forgot about stimulus_reflex, so it broke there. This PR fixes that.  
Fixes # (issue)
Fixes #107 
Explain value.

Fix the omission of the stimulus_reflex variable

---

docs/SUMMARY.md
docs/security.md
sockpuppet/routing.py

Make sure that the sockpuppet is secure against CSRF attacks
by default. This also starts the documentation around security
and authentication that can be expanded upon.
Fixes # (issue)
Fixes #104

CSRF validator and documentation for security

---

webpack.config.js

just to satisfy ESLint, as isProd is used twice and has no let/const keyword.
Just to simplify code, and make ESLint happy.

extract/const isProd

---

sockpuppet/reflex.py

Figuring out which view it is and adding the correct property to
that view is better than trying to re-render the view itself.
This should solve for django's generic views. It won't work
for Django vanilla views package, but we can deal with this
later if someone show interest for that.
It removes the rendering of the view once, so it will be marginally faster. It also makes it 
easier to reason about what is happening.

Don't call get_context_data more than necessary

---

.github/workflows/build.yml
tox.ini

Adds CI for django 3.2
So that we know for sure that everything works in the most recent release of django.

CI for django 3.2

---

.github/workflows/build.yml
tox.ini

Channels 2.4 is proving problematic in CI, and it's not worth
the effort to maintain that. Sockpuppet should still work for
channels 2.4, but given we don't run a CI for it we can't make
any promises for it.

Remove Channels 2.4 in CI

---

sockpuppet/consumer.py

For any usage < 3.8 it won't emit a browser error due the [following bug in python](https://bugs.python.org/issue17396), however for python >= 3.8 it will emit an console log error in the browser stating `Reflex couldn't be loaded: (start of python error here).`
Perhaps you can give this a try @nerdoc if you've got the chance? You could install it through the following command. 
```
pip install https://github.com/jonathan-s/django-sockpuppet/archive/reflex-load-error.zip
```
Fixes #137 
Clearer errors are better.

Emit browser console error when a reflex can't be loaded

---

sockpuppet/channel.py

- Allow channel methods to be chained
- Improve the doc strings with updated docs from cable ready.
- Allow keyword arguments for each method that will be used in options.
Even if the Channel is largely undocumented, we can at least improve the documentation strings for it to be clearer what kind of options the different methods take.

Improved doc strings in Channel + method chaining
